# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration. Last update Jari, 2016-04-01.
# The "2" in Vagrant.configure configures the configuration version, please don't change it!
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "lo-vagrant"
  config.vm.provider "virtualbox" do |vb|
     ## Display the VirtualBox GUI when booting the machine
     #vb.gui = true
     vb.memory = 1024
     vb.cpus = 1
     vb.name = "lo_jee_ref"
  end
  
  ## Network
  config.vm.network "forwarded_port", guest: 5432, host: 15432
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9990, host: 9990
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  
  ## Share an additional folder to the guest VM
  config.vm.synced_folder "../environment", "/vagrant/configurations/environment"
  config.vm.synced_folder "../shared", "/vagrant/configurations/shared"
  
  ## Shell provisioning
  #config.vm.provision "shell", path: "provisioner/shell/update-guest-os.sh"
  config.vm.provision "shell", path: "provisioner/shell/install-platform.sh"
  config.vm.provision "shell", path: "provisioner/shell/install-application.sh"
  #config.vm.provision "shell", path: "provisioner/shell/run-system.sh"
end
